packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@eslint/json@2.1.0'
  - globals@17.12.0
  - '@types/node@26.4.1'

savePrefix: ''
