import type {Config} from "prettier";

const config: Config = {
  arrowParens: "always",
  bracketSameLine: true,
  bracketSpacing: false,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  jsxSingleQuote: false,
  printWidth: 120,
  proseWrap: "always",
  quoteProps: "as-needed",
  semi: true,
  singleAttributePerLine: false,
  singleQuote: false,
  tabWidth: 10,
  trailingComma: "none",
  useTabs: false

  //   plugins: ["@ianvs/prettier-plugin-sort-imports"],
  //   importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  //   importOrderTypeScriptVersion: "5.0.0",
  //   importOrder: [
  //     "<BUILT_IN_MODULES>",
  //     "",
  //     "^react$",
  //     "",
  //     "<THIRD_PARTY_MODULES>",
  //     "",
  //     "^@/providers/(.*)$",
  //     "",
  //     "^@/containers/(.*)$",
  //     "",
  //     "^@/components/(.*)$",
  //     "",
  //     "^@/hooks/(.*)$",
  //     "",
  //     "^@/services/(.*)$",
  //     "",
  //     "^@/serverActions/(.*)$",
  //     "",
  //     "^@/constants/(.*)$",
  //     "",
  //     "^@/(.*)$",
  //     "",
  //     "^[./]",
  //     "",
  //     "<TYPES>",
  //     "<TYPES>^[.]",
  //     "",
  //     "^(?!.*[.]css$)[./].*$",
  //     ".css$",
  //   ],
};

export default config;
